from fastapi import APIRouter

marketplace_router = APIRouter(prefix="/api/marketplace")

MCP_CATALOG = [
    {
        "id": "clickmassa",
        "name": "ClickMassa CRM",
        "description": "Controle total do seu CRM ClickMassa. Gerencie contatos, tickets, mensagens, automações e funis via IA.",
        "category": "crm",
        "icon": "database",
        "color": "#F97316",
        "status": "active",
        "version": "2.0",
        "author": "GapHub",
        "installs": 1240,
        "rating": 4.9,
        "credentials_required": ["base_url", "email", "password"],
        "tools": [
            {"name": "buscar_contato_por_numero", "description": "Busca contato por número de WhatsApp"},
            {"name": "buscar_contato_por_id", "description": "Busca contato por ID interno"},
            {"name": "listar_contatos", "description": "Lista todos os contatos"},
            {"name": "criar_contato", "description": "Cria novo contato"},
            {"name": "atualizar_contato", "description": "Atualiza dados do contato"},
            {"name": "adicionar_etiquetas", "description": "Adiciona etiquetas ao contato"},
            {"name": "enviar_mensagem", "description": "Envia mensagem via push API"},
            {"name": "enviar_mensagem_direta", "description": "Envia mensagem como usuário logado (sem créditos)"},
            {"name": "enviar_nota_interna", "description": "Envia nota interna no ticket"},
            {"name": "listar_tickets_pendentes", "description": "Lista tickets na fila de espera"},
            {"name": "listar_tickets_abertos", "description": "Lista tickets em atendimento"},
            {"name": "fechar_ticket", "description": "Encerra atendimento"},
            {"name": "devolver_para_fila", "description": "Devolve ticket para fila"},
            {"name": "listar_status_lead", "description": "Lista fases do funil de vendas"},
            {"name": "listar_origens_lead", "description": "Lista origens de leads"},
            {"name": "criar_tarefa", "description": "Cria tarefa, ligação ou compromisso"},
            {"name": "listar_tarefas", "description": "Lista tarefas agendadas"},
            {"name": "listar_conexoes_whatsapp", "description": "Lista canais de WhatsApp"},
            {"name": "listar_fluxos_chat", "description": "Lista chatbots nativos"},
            {"name": "atribuir_fluxo_chat", "description": "Ativa/desativa chatbot"},
            {"name": "listar_funis", "description": "Lista funis de follow-up"},
            {"name": "criar_funil", "description": "Cria funil de follow-up"},
            {"name": "atribuir_funil_contato", "description": "Insere lead em funil"},
        ],
    },
    {
        "id": "web_search",
        "name": "Busca na Web",
        "description": "Permite que a IA pesquise informações em tempo real na internet para enriquecer respostas.",
        "category": "search",
        "icon": "search",
        "color": "#3B82F6",
        "status": "active",
        "version": "1.0",
        "author": "GapHub",
        "installs": 890,
        "rating": 4.7,
        "credentials_required": [],
        "tools": [
            {"name": "buscar_web", "description": "Pesquisa na internet e retorna resultados relevantes"},
        ],
    },
    {
        "id": "http_request",
        "name": "HTTP Request",
        "description": "Faça requisições HTTP/REST para qualquer API externa. Ideal para integrações personalizadas.",
        "category": "developer",
        "icon": "globe",
        "color": "#8B5CF6",
        "status": "active",
        "version": "1.0",
        "author": "GapHub",
        "installs": 675,
        "rating": 4.8,
        "credentials_required": [],
        "tools": [
            {"name": "http_get", "description": "Requisição GET para uma URL"},
            {"name": "http_post", "description": "Requisição POST com payload JSON"},
        ],
    },
    {
        "id": "whatsapp_evolution",
        "name": "WhatsApp Evolution",
        "description": "Integração direta com WhatsApp via Evolution API. Envio de mensagens, mídia e gerenciamento de grupos.",
        "category": "communication",
        "icon": "message-circle",
        "color": "#10B981",
        "status": "coming_soon",
        "version": "1.0",
        "author": "GapHub",
        "installs": 0,
        "rating": 0,
        "credentials_required": ["api_url", "api_key", "instance_name"],
        "tools": [],
    },
    {
        "id": "google_calendar",
        "name": "Google Calendar",
        "description": "Crie eventos, consulte agendas e gerencie compromissos diretamente pelo agente de IA.",
        "category": "productivity",
        "icon": "calendar",
        "color": "#4285F4",
        "status": "coming_soon",
        "version": "1.0",
        "author": "GapHub",
        "installs": 0,
        "rating": 0,
        "credentials_required": ["oauth_token"],
        "tools": [],
    },
    {
        "id": "gmail",
        "name": "Gmail",
        "description": "Envie, leia e organize emails diretamente pelo agente. Perfeito para automações de follow-up.",
        "category": "communication",
        "icon": "mail",
        "color": "#EA4335",
        "status": "coming_soon",
        "version": "1.0",
        "author": "GapHub",
        "installs": 0,
        "rating": 0,
        "credentials_required": ["oauth_token"],
        "tools": [],
    },
    {
        "id": "n8n_webhook",
        "name": "N8N Webhook",
        "description": "Dispare e receba webhooks do N8N para integrar com qualquer fluxo de automação existente.",
        "category": "automation",
        "icon": "zap",
        "color": "#FF6D00",
        "status": "coming_soon",
        "version": "1.0",
        "author": "GapHub",
        "installs": 0,
        "rating": 0,
        "credentials_required": ["webhook_url"],
        "tools": [],
    },
    {
        "id": "telegram_bot",
        "name": "Telegram Bot",
        "description": "Conecte o agente ao Telegram para receber comandos e enviar notificações automáticas.",
        "category": "communication",
        "icon": "send",
        "color": "#2AABEE",
        "status": "coming_soon",
        "version": "1.0",
        "author": "GapHub",
        "installs": 0,
        "rating": 0,
        "credentials_required": ["bot_token"],
        "tools": [],
    },
    {
        "id": "stripe",
        "name": "Stripe Payments",
        "description": "Consulte pagamentos, crie links de pagamento e gerencie assinaturas via IA.",
        "category": "finance",
        "icon": "credit-card",
        "color": "#635BFF",
        "status": "coming_soon",
        "version": "1.0",
        "author": "GapHub",
        "installs": 0,
        "rating": 0,
        "credentials_required": ["api_key"],
        "tools": [],
    },
    {
        "id": "github",
        "name": "GitHub",
        "description": "Gerencie repositórios, issues e pull requests diretamente pelo agente de IA.",
        "category": "developer",
        "icon": "github",
        "color": "#ffffff",
        "status": "coming_soon",
        "version": "1.0",
        "author": "GapHub",
        "installs": 0,
        "rating": 0,
        "credentials_required": ["access_token"],
        "tools": [],
    },
    {
        "id": "slack",
        "name": "Slack",
        "description": "Envie mensagens, leia canais e responda notificações no Slack com agentes autônomos.",
        "category": "communication",
        "icon": "hash",
        "color": "#4A154B",
        "status": "coming_soon",
        "version": "1.0",
        "author": "GapHub",
        "installs": 0,
        "rating": 0,
        "credentials_required": ["bot_token", "channel_id"],
        "tools": [],
    },
]

CATEGORIES = [
    {"id": "all", "label": "Todos"},
    {"id": "crm", "label": "CRM"},
    {"id": "communication", "label": "Comunicação"},
    {"id": "productivity", "label": "Produtividade"},
    {"id": "automation", "label": "Automação"},
    {"id": "developer", "label": "Developer"},
    {"id": "finance", "label": "Finanças"},
    {"id": "search", "label": "Busca"},
]


@marketplace_router.get("")
async def list_mcps(category: str = "all", search: str = ""):
    items = MCP_CATALOG
    if category != "all":
        items = [m for m in items if m["category"] == category]
    if search:
        s = search.lower()
        items = [m for m in items if s in m["name"].lower() or s in m["description"].lower()]
    return {"mcps": items, "categories": CATEGORIES, "total": len(items)}


@marketplace_router.get("/{mcp_id}")
async def get_mcp(mcp_id: str):
    mcp = next((m for m in MCP_CATALOG if m["id"] == mcp_id), None)
    if not mcp:
        raise HTTPException(status_code=404, detail="MCP não encontrado")
    return mcp
